baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nushell"
theme = "nu"

[params]
    description = "The modern and powerful shell."

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
#
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
        weight = -110

      [[languages.en.menu.main]]
        identifier = "docs"
        name = "docs"
        url = "/docs"
        weight = -100

      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/nushell/nushell"
        weight = -90
#
  [languages.tpo]
    contentDir = "content/tpo"
    languageName = "toki pona"
    weight = 2
#
      [[languages.tpo.menu.main]]
        identifier = "home"
        name = "open"
        url = "/tpo"
        weight = -110

      [[languages.tpo.menu.main]]
        identifier = "docs"
        name = "tomo sona"
        url = "/tpo/docs"
        weight = -100

      [[languages.tpo.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/nushell/nushell"
        weight = -90
#
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 3
#
      [[languages.es.menu.main]]
        identifier = "home"
        name = "home"
        url = "/es"
        weight = -110

      [[languages.es.menu.main]]
        identifier = "docs"
        name = "docs"
        url = "/es/docs"
        weight = -100

      [[languages.es.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/nushell/nushell"
        weight = -90
#